var ProductConstants = {
  RECEIVE_ALL_ITEMS: "RECEIVE_ALL_ITEMS",
  RECEIVE_FILTERED_ITEMS: "RECEIVE_FILTERED_ITEMS",
  PRODUCT_CREATED: "PRODUCT_CREATED",
  PRODUCTS_SEARCH: "PRODUCTS_SEARCH",
  AUCTION_PRODUCTS_RECEIVED: "AUCTION_PRODUCTS_RECEIVED"
};

module.exports = ProductConstants;
