var ProductConstants = {
  RECEIVE_ALL_ITEMS: "RECEIVE_ALL_ITEMS",
  RECEIVE_FILTERED_ITEMS: "RECEIVE_FILTERED_ITEMS",
  PRODUCT_CREATED: "PRODUCT_CREATED",
  EDIT_PRODUCTS_SEARCH: "EDIT_PRODUCTS_SEARCH"
};

module.exports = ProductConstants;
